package nz.ac.cjlu.vocabmaster.controller;

import nz.ac.cjlu.vocabmaster.model.Word;
import nz.ac.cjlu.vocabmaster.dao.UserWordDAO;
import nz.ac.cjlu.vocabmaster.dao.WordDAO;
import nz.ac.cjlu.vocabmaster.view.StudyPanel;
import nz.ac.cjlu.vocabmaster.service.StudyService;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;

// StudyController.java
// Core business logic for study mode.
// Delegates to StudyService for algorithms: random word selection, status update.
// Implements the exact 3-stage workflow as specified.
// Generated by ChatGPT for button logic and stage transitions (with minor modifications for integration).
public class StudyController {
    private StudyPanel view;
    private StudyService service;
    private int userId;
    private Word currentWord;

    public StudyController(StudyPanel view, int userId) {
        this.view = view;
        this.userId = userId;
        this.service = new StudyService(new UserWordDAO(), new WordDAO());

        loadNextWord();  // Initial load: stage 1

        view.addListeners(
            e -> showStage2(),  // Show example (English only)
            e -> handleKnown(true),  // I know it
            e -> handleKnown(false),  // I don't know it
            e -> loadNextWord()  // Next word
        );
    }

    private void loadNextWord() {
        currentWord = service.getRandomUnknownWord(userId);
        if (currentWord == null) {
            JOptionPane.showMessageDialog(view, "All words mastered! Great job!");
            return;
        }
        view.resetStage1(currentWord);
    }

    private void showStage2() {
        view.showStage2(currentWord.getExampleEn());
    }

    private void handleKnown(boolean isKnown) {
        service.updateWordStatus(userId, currentWord.getId(), isKnown);
        view.showStage3(currentWord.getExampleCn(), currentWord.getChinese(), isKnown);
    }
}